CREATE TABLE IF NOT EXISTS event_ratings (
    rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating_type VARCHAR(10) NOT NULL,
    CONSTRAINT uq_event_rating UNIQUE (event_id, user_id),
    CONSTRAINT chk_rating_type CHECK (rating_type IN ('LIKE', 'DISLIKE'))
);

CREATE TABLE IF NOT EXISTS subscriptions (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL,
    follower_name VARCHAR(250) NOT NULL,
    followed_id BIGINT NOT NULL,
    followed_name VARCHAR(250) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
    created TIMESTAMP NOT NULL,
    UNIQUE(follower_id, followed_id)
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(7000) NOT NULL,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    author_name VARCHAR(250) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated TIMESTAMP WITHOUT TIME ZONE
);


CREATE INDEX IF NOT EXISTS idx_comments_event ON comments(event_id);
CREATE INDEX IF NOT EXISTS idx_comments_author ON comments(author_id);
CREATE INDEX IF NOT EXISTS idx_ratings_event ON event_ratings(event_id);
