services:
  discovery-server:
    build:
      context: .
      dockerfile: infra/discovery-server/Dockerfile
    ports:
      - "8761:8761"
    environment:
      EUREKA_HOST: discovery-server
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8761/actuator/health"]
      interval: 3s
      timeout: 3s
      start_period: 30s
      retries: 20
  config-server:
    build:
      context: .
      dockerfile: infra/config-server/Dockerfile
    environment:
      EUREKA_URL: http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
  gateway-server:
    build:
      context: .
      dockerfile: infra/gateway-server/Dockerfile
    ports:
      - "8080:8080"
      - "9090:8080"
    environment:
      EUREKA_URL: http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_started
      ewm-service:
        condition: service_healthy
      stats-server:
        condition: service_healthy
  stats-server:
    build:
      context: .
      dockerfile: stats/stats-server/Dockerfile
    environment:
      EUREKA_URL: http://discovery-server:8761/eureka/
      STATS_DATABASE_URL: jdbc:postgresql://stats-db:5432/ewm-stats
      MANAGEMENT_SERVER_PORT: 8081
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 3s
      start_period: 60s
      retries: 20
    depends_on:
      config-server:
        condition: service_started
      stats-db:
        condition: service_healthy
  ewm-service:
    build:
      context: .
      dockerfile: core/main-service/Dockerfile
    environment:
      EUREKA_URL: http://discovery-server:8761/eureka/
      MAIN_DATABASE_URL: jdbc:postgresql://ewm-db:5432/ewm-main
      MANAGEMENT_SERVER_PORT: 8081
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 3s
      start_period: 60s
      retries: 20
    depends_on:
      config-server:
        condition: service_started
      ewm-db:
        condition: service_healthy
  stats-db:
    image: postgres:16.1
    ports:
      - "6541:5432"
    environment:
      POSTGRES_PASSWORD: ewm
      POSTGRES_USER: ewm
      POSTGRES_DB: ewm-stats
    volumes:
      - stats_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10
  ewm-db:
    image: postgres:16.1
    ports:
      - "6542:5432"
    environment:
      POSTGRES_PASSWORD: ewm
      POSTGRES_USER: ewm
      POSTGRES_DB: ewm-main
    volumes:
      - ewm_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10
volumes:
  stats_db_data:
  ewm_db_data:
