CREATE TABLE IF NOT EXISTS participation_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT uq_request UNIQUE (requester_id, event_id)
);


CREATE INDEX IF NOT EXISTS idx_requests_event_status ON participation_requests(event_id, status);
