server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: stats-service-api
          uri: lb://stats-server
          predicates:
            - Path=/hit,/stats
        - id: main-service-api
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**,/locations/**
eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
